### ISSUE TITLE
突然发现没有数据库这玩意

### ISSUE THREAD

**Issue by xuzuxing** [oubingbing/school#1]
只能默默重写了吗 大哥？

**Comment by oubingbing** [comment]
您好，我不是很清楚您再说什么，我这个项目是有数据库的，您安装composer后运行composer install命令安装框架，然后配置好数据信息，再运行php artisan migrate，所有的数据表就都有了。如果还有不清楚的可以继续问下我。

**Comment by xuzuxing** [comment]
噢！我composer install了  但是忘记artisan migrate了，瞧我这....尴尬的

**Comment by oubingbing** [comment]
哈哈，没事
